In [3]:
! pip install numpy
! pip install scipy


[notice] A new release of pip is available: 23.2.1 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.2.1 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

In [ ]:
1==[1,2,3]
a=np.array(1)
a1=np.array([1,2,3,4,5])
a1


array([1, 2, 3, 4, 5])

In [7]:
1==[1,2,3]
a=np.array(1)
a1=np.array([1,2,3,4,5])
a1.shape

(5,)

In [8]:
1==[1,2,3]
a=np.array(1)
a1=np.array([1,2,3,4,5])
a1.size

5

In [9]:
x=np.arange(0,11,2)
x

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.zeros([10,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones([10,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [44]:
np.random.randn(3,4)
np.random.randint(1,10,3)

array([9, 7, 5], dtype=int32)

In [48]:
np.random.randint(1,10,3)

array([6, 5, 7], dtype=int32)

In [5]:
1==[1,2,3]
a=np.array(1)
a1=np.array([[1,2,3,4,5],[1,2,4,4,4]])
a1


array([[1, 2, 3, 4, 5],
       [1, 2, 4, 4, 4]])

In [6]:
1==[1,2,3]
a=np.array(1)
a1=np.array([[[1,2,3,4,5],[1,2,4,4,4]]])
a1 

array([[[1, 2, 3, 4, 5],
        [1, 2, 4, 4, 4]]])

In [14]:
x=np.arange(0,11,2)
x

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [17]:
np.ones([2,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [22]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [67]:
np.random.rand(3,4)

array([[0.42287765, 0.17052861, 0.64761617, 0.06805914],
       [0.55788937, 0.29340793, 0.12097854, 0.65324037],
       [0.44201612, 0.71993312, 0.36095169, 0.23830623]])

In [87]:
np.random.randint(1,10,3)

array([1, 7, 4], dtype=int32)

In [91]:
a2=np.arange(25)
a2.shape

(25,)

In [52]:
a2=np.arange(25)
a3=a2.reshape(5,5)
a3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
a4=np.random.randint(1,100,20)
a4

array([20, 12, 12, 12, 67, 87, 33, 24, 49, 97, 35, 70, 25, 33, 48, 36, 74,
        9,  6,  5], dtype=int32)

In [71]:
a4.max()

np.int32(97)

In [72]:
a4.argmax()

np.int64(9)

In [73]:
a4.min()

np.int32(5)

In [76]:
a4.argmin()

np.int64(19)

In [80]:
a4=a4.reshape(4,5)
a4

array([[20, 12, 12, 12, 67],
       [87, 33, 24, 49, 97],
       [35, 70, 25, 33, 48],
       [36, 74,  9,  6,  5]], dtype=int32)

In [81]:
a4[0,2]

np.int32(12)

In [85]:
a6=np.arange(25)
a5=a4.reshape(4,5)
a5

array([[20, 12, 12, 12, 67],
       [87, 33, 24, 49, 97],
       [35, 70, 25, 33, 48],
       [36, 74,  9,  6,  5]], dtype=int32)

In [95]:
a5[1:,4]

array([97, 48,  5], dtype=int32)

In [97]:
a5[[1,2]]

array([[87, 33, 24, 49, 97],
       [35, 70, 25, 33, 48]], dtype=int32)

In [98]:
a5[[1,2],:3]

array([[87, 33, 24],
       [35, 70, 25]], dtype=int32)

In [99]:
a5[[1,3]],[[1,3]]

(array([[87, 33, 24, 49, 97],
        [36, 74,  9,  6,  5]], dtype=int32),
 [[1, 3]])